"""
Document type catalog for DocuMind AI.

Each entry defines:
  - key, label, category, subtitle, accent, tag, icon (frontend hint)
  - fields  : the initial form inputs we ask up-front
  - sections: ordered list of section headings the generator MUST output
  - guidance: per-type extra direction passed to the LLM
"""

CATEGORIES = {
    "ba":  "Business Analysis",
    "pm":  "Project Management",
    "qa":  "Quality Assurance",
    "ops": "Operations",
    "mfg": "Manufacturing",
    "hr":  "Human Resources",
}

INDUSTRIES = [
    "IT", "Manufacturing", "Finance", "HR", "Healthcare", "Logistics",
    "Retail", "Education", "Telecom", "Energy",
]

DOC_TYPES = {
    # ---------------- Business Analysis ----------------
    "brd": {
        "label": "BRD Generator", "category": "ba", "subtitle": "Business Requirements Document",
        "accent": "#A8E6CF", "tag": "Strategy", "icon": "FileText",
        "fields": [
            {"name": "Project Name", "type": "text", "required": True, "placeholder": "Customer Onboarding Revamp"},
            {"name": "Industry", "type": "select", "options": INDUSTRIES, "placeholder": "Select industry"},
            {"name": "Department", "type": "text", "placeholder": "Operations / IT / Finance…"},
            {"name": "Business Problem", "type": "textarea", "rows": 3},
            {"name": "Current Process", "type": "textarea", "rows": 3},
            {"name": "Pain Points", "type": "textarea", "rows": 2},
            {"name": "Proposed Solution", "type": "textarea", "rows": 3},
            {"name": "Stakeholders", "type": "textarea", "rows": 2},
            {"name": "Business Objectives", "type": "textarea", "rows": 2},
            {"name": "Functional Requirements", "type": "textarea", "rows": 3},
            {"name": "Non Functional Requirements", "type": "textarea", "rows": 2},
            {"name": "Assumptions", "type": "textarea", "rows": 2},
            {"name": "Constraints", "type": "textarea", "rows": 2},
            {"name": "Risks", "type": "textarea", "rows": 2},
            {"name": "Success Metrics", "type": "textarea", "rows": 2},
        ],
        "sections": ["Executive Summary", "Business Background", "Problem Statement", "Objectives",
                     "Scope", "Stakeholders", "Functional Requirements", "Non Functional Requirements",
                     "Assumptions", "Constraints", "Success Metrics", "Risks", "Recommendations"],
    },
    "frd": {
        "label": "FRD Generator", "category": "ba", "subtitle": "Functional Requirements Document",
        "accent": "#B5EAD7", "tag": "Specification", "icon": "FileSpreadsheet",
        "fields": [
            {"name": "Project Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Module / Feature", "type": "text"},
            {"name": "Source BRD Summary", "type": "textarea", "rows": 4},
            {"name": "Functional Requirements", "type": "textarea", "rows": 4},
            {"name": "User Roles", "type": "textarea", "rows": 2},
            {"name": "Data Inputs", "type": "textarea", "rows": 2},
            {"name": "Data Outputs", "type": "textarea", "rows": 2},
            {"name": "Business Rules", "type": "textarea", "rows": 3},
            {"name": "Integrations", "type": "textarea", "rows": 2},
        ],
        "sections": ["Document Purpose", "System Overview", "Functional Requirements (Detailed)",
                     "Use Cases", "Business Rules", "Data Requirements", "Interface Requirements",
                     "Reporting Requirements", "Assumptions & Dependencies", "Acceptance Criteria"],
    },
    "srs": {
        "label": "SRS Generator", "category": "ba", "subtitle": "Software Requirements Specification",
        "accent": "#C7CEEA", "tag": "Engineering", "icon": "Code2",
        "fields": [
            {"name": "Product Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Intended Audience", "type": "text"},
            {"name": "Product Scope", "type": "textarea", "rows": 3},
            {"name": "User Classes", "type": "textarea", "rows": 2},
            {"name": "Operating Environment", "type": "textarea", "rows": 2},
            {"name": "Functional Requirements", "type": "textarea", "rows": 4},
            {"name": "Non Functional Requirements", "type": "textarea", "rows": 3},
            {"name": "External Interfaces", "type": "textarea", "rows": 2},
        ],
        "sections": ["Introduction", "Overall Description", "System Features",
                     "External Interface Requirements", "Functional Requirements",
                     "Non-Functional Requirements", "Other Requirements", "Appendix"],
    },
    "user-story": {
        "label": "User Story Generator", "category": "ba", "subtitle": "Agile User Stories",
        "accent": "#A8C6F7", "tag": "Product", "icon": "BookUser",
        "fields": [
            {"name": "Project Name", "type": "text", "required": True},
            {"name": "Feature Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "User Type", "type": "text"},
            {"name": "Business Goal", "type": "textarea", "rows": 2},
            {"name": "Acceptance Criteria", "type": "textarea", "rows": 3},
            {"name": "Dependencies", "type": "textarea", "rows": 2},
        ],
        "sections": ["User Stories", "Acceptance Criteria", "Edge Cases",
                     "Success Scenarios", "Failure Scenarios"],
        "guidance": "User Stories MUST follow the strict format 'As a [User], I want [Goal], So that [Benefit]'. Generate 4-7 stories.",
    },
    "use-case": {
        "label": "Use Case Generator", "category": "ba", "subtitle": "Use Case Specifications",
        "accent": "#D5C5F7", "tag": "Modeling", "icon": "Workflow",
        "fields": [
            {"name": "System Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Primary Actor", "type": "text"},
            {"name": "Secondary Actors", "type": "text"},
            {"name": "Goal / Scenario", "type": "textarea", "rows": 3},
            {"name": "Preconditions", "type": "textarea", "rows": 2},
            {"name": "Postconditions", "type": "textarea", "rows": 2},
        ],
        "sections": ["Use Case Name", "Actors", "Description", "Preconditions",
                     "Main Flow", "Alternate Flows", "Exception Flows",
                     "Postconditions", "Business Rules"],
    },

    # ---------------- Project Management ----------------
    "project-charter": {
        "label": "Project Charter", "category": "pm", "subtitle": "Initiation Charter",
        "accent": "#FFE45E", "tag": "Initiation", "icon": "Flag",
        "fields": [
            {"name": "Project Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Sponsor", "type": "text"},
            {"name": "Project Manager", "type": "text"},
            {"name": "Business Need", "type": "textarea", "rows": 3},
            {"name": "Objectives", "type": "textarea", "rows": 2},
            {"name": "Scope (In/Out)", "type": "textarea", "rows": 3},
            {"name": "Key Milestones", "type": "textarea", "rows": 2},
            {"name": "Budget Estimate", "type": "text"},
            {"name": "Key Risks", "type": "textarea", "rows": 2},
        ],
        "sections": ["Project Purpose", "Business Need & Justification", "Objectives & Success Criteria",
                     "Scope", "Deliverables", "High-Level Timeline", "Budget Summary",
                     "Stakeholders", "Risks & Assumptions", "Approval"],
    },
    "risk-register": {
        "label": "Risk Register", "category": "pm", "subtitle": "Project Risk Log",
        "accent": "#FFB6C1", "tag": "Risk", "icon": "AlertTriangle",
        "fields": [
            {"name": "Project Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Known Risks", "type": "textarea", "rows": 5},
            {"name": "Risk Owners", "type": "textarea", "rows": 2},
            {"name": "Mitigation Strategies", "type": "textarea", "rows": 3},
        ],
        "sections": ["Overview", "Risk Categorization", "Risk Register (Table)",
                     "Top Risks", "Mitigation Plans", "Monitoring Approach"],
        "guidance": "Render the 'Risk Register (Table)' as a Markdown table with columns: ID | Risk | Category | Likelihood | Impact | Score | Owner | Mitigation. Include 6-10 rows.",
    },
    "raid-log": {
        "label": "RAID Log", "category": "pm", "subtitle": "Risks / Actions / Issues / Decisions",
        "accent": "#FFD3B6", "tag": "Tracking", "icon": "ListChecks",
        "fields": [
            {"name": "Project Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Risks", "type": "textarea", "rows": 3},
            {"name": "Actions", "type": "textarea", "rows": 3},
            {"name": "Issues", "type": "textarea", "rows": 3},
            {"name": "Decisions", "type": "textarea", "rows": 3},
        ],
        "sections": ["Overview", "Risks (Table)", "Actions (Table)",
                     "Issues (Table)", "Decisions (Table)", "Summary & Next Steps"],
        "guidance": "Each (Table) section must be rendered as a Markdown table. Use columns appropriate to each category and include 4-8 example rows.",
    },
    "stakeholder-matrix": {
        "label": "Stakeholder Matrix", "category": "pm", "subtitle": "Stakeholder Analysis",
        "accent": "#A8C6F7", "tag": "Engagement", "icon": "Users",
        "fields": [
            {"name": "Project Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Stakeholders", "type": "textarea", "rows": 4},
            {"name": "Influence Drivers", "type": "textarea", "rows": 2},
        ],
        "sections": ["Overview", "Stakeholder List (Table)", "Power / Interest Grid",
                     "Engagement Strategy", "Communication Plan"],
        "guidance": "Stakeholder List must be a Markdown table: Name | Role | Department | Interest | Influence | Engagement Strategy.",
    },
    "scope-document": {
        "label": "Scope Document", "category": "pm", "subtitle": "Scope Definition",
        "accent": "#A8E6CF", "tag": "Planning", "icon": "Crosshair",
        "fields": [
            {"name": "Project Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "In Scope", "type": "textarea", "rows": 3},
            {"name": "Out of Scope", "type": "textarea", "rows": 3},
            {"name": "Deliverables", "type": "textarea", "rows": 2},
            {"name": "Assumptions", "type": "textarea", "rows": 2},
            {"name": "Constraints", "type": "textarea", "rows": 2},
        ],
        "sections": ["Project Overview", "Scope Statement", "In Scope", "Out of Scope",
                     "Deliverables", "Acceptance Criteria", "Assumptions", "Constraints",
                     "Change Control"],
    },

    # ---------------- Quality Assurance ----------------
    "test-case": {
        "label": "Test Case Generator", "category": "qa", "subtitle": "QA Test Cases",
        "accent": "#FFE45E", "tag": "Quality", "icon": "FlaskConical",
        "fields": [
            {"name": "Application Name", "type": "text", "required": True},
            {"name": "Feature", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Requirement Description", "type": "textarea", "rows": 4},
            {"name": "Expected Behaviour", "type": "textarea", "rows": 3},
        ],
        "sections": ["Test Case ID", "Test Scenario", "Preconditions", "Test Steps",
                     "Expected Result", "Priority", "Test Data"],
        "guidance": "Generate 6-10 distinct test cases. In 'Test Steps' render each test case (TC-01, TC-02, …) as a numbered block with its own preconditions, steps, and expected result. Use a Markdown table where helpful.",
    },
    "test-plan": {
        "label": "Test Plan", "category": "qa", "subtitle": "QA Test Plan",
        "accent": "#FFE0B2", "tag": "Planning", "icon": "ClipboardCheck",
        "fields": [
            {"name": "Project Name", "type": "text", "required": True},
            {"name": "Release Name", "type": "text"},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Scope of Testing", "type": "textarea", "rows": 3},
            {"name": "Types of Testing", "type": "textarea", "rows": 2},
            {"name": "Entry Criteria", "type": "textarea", "rows": 2},
            {"name": "Exit Criteria", "type": "textarea", "rows": 2},
        ],
        "sections": ["Introduction", "Scope", "Test Objectives", "Test Approach",
                     "Test Deliverables", "Entry & Exit Criteria", "Test Environment",
                     "Roles & Responsibilities", "Schedule", "Risks & Mitigation"],
    },
    "test-strategy": {
        "label": "Test Strategy", "category": "qa", "subtitle": "Org-wide Test Strategy",
        "accent": "#FFCDD2", "tag": "Strategy", "icon": "Target",
        "fields": [
            {"name": "Organization / Program", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Quality Objectives", "type": "textarea", "rows": 3},
            {"name": "Test Types in Scope", "type": "textarea", "rows": 2},
            {"name": "Automation Goals", "type": "textarea", "rows": 2},
            {"name": "Tools & Platforms", "type": "textarea", "rows": 2},
        ],
        "sections": ["Purpose", "Scope", "Quality Goals", "Testing Levels",
                     "Test Types", "Automation Strategy", "Tooling", "Metrics & KPIs",
                     "Governance", "Continuous Improvement"],
    },
    "rtm": {
        "label": "Requirement Traceability Matrix", "category": "qa", "subtitle": "RTM",
        "accent": "#D1C4E9", "tag": "Traceability", "icon": "Network",
        "fields": [
            {"name": "Project Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Requirement Source", "type": "text", "placeholder": "BRD / FRD / Story IDs"},
            {"name": "Requirements", "type": "textarea", "rows": 5},
            {"name": "Test References", "type": "textarea", "rows": 3},
        ],
        "sections": ["Overview", "Traceability Matrix", "Coverage Analysis", "Gaps & Risks"],
        "guidance": "The 'Traceability Matrix' MUST be a Markdown table with columns: Req ID | Requirement | Source | Test Case ID(s) | Status | Coverage. Include 6-12 rows.",
    },
    "defect-report": {
        "label": "Defect Report", "category": "qa", "subtitle": "Bug / Defect Report",
        "accent": "#FFB6C1", "tag": "Defect", "icon": "Bug",
        "fields": [
            {"name": "Application Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Environment", "type": "text"},
            {"name": "Steps Observed", "type": "textarea", "rows": 4},
            {"name": "Expected Behaviour", "type": "textarea", "rows": 2},
            {"name": "Actual Behaviour", "type": "textarea", "rows": 2},
            {"name": "Severity", "type": "text"},
        ],
        "sections": ["Summary", "Environment Details", "Steps to Reproduce",
                     "Expected vs Actual", "Severity & Priority", "Attachments / Logs",
                     "Workaround", "Root Cause Hypothesis", "Recommended Fix"],
    },

    # ---------------- Operations ----------------
    "sop": {
        "label": "SOP Generator", "category": "ops", "subtitle": "Standard Operating Procedure",
        "accent": "#FFD3B6", "tag": "Operations", "icon": "ClipboardList",
        "fields": [
            {"name": "Process Name", "type": "text", "required": True},
            {"name": "Department", "type": "text"},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Purpose", "type": "textarea", "rows": 2},
            {"name": "Scope", "type": "textarea", "rows": 2},
            {"name": "Roles and Responsibilities", "type": "textarea", "rows": 3},
            {"name": "Required Equipment", "type": "textarea", "rows": 2},
            {"name": "Safety Precautions", "type": "textarea", "rows": 2},
            {"name": "Frequency", "type": "text"},
            {"name": "Step-by-Step Process", "type": "textarea", "rows": 4},
            {"name": "Acceptance Criteria", "type": "textarea", "rows": 2},
            {"name": "Escalation Procedure", "type": "textarea", "rows": 2},
        ],
        "sections": ["Purpose", "Scope", "Responsibilities", "Materials Required",
                     "Safety Guidelines", "Procedure Steps", "Quality Checks",
                     "Escalation Matrix", "Revision History"],
    },
    "work-instruction": {
        "label": "Work Instruction", "category": "ops", "subtitle": "Detailed Work Steps",
        "accent": "#FFE0B2", "tag": "Execution", "icon": "Wrench",
        "fields": [
            {"name": "Task Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Operator Role", "type": "text"},
            {"name": "Tools / Equipment", "type": "textarea", "rows": 2},
            {"name": "Steps", "type": "textarea", "rows": 4},
            {"name": "Safety Notes", "type": "textarea", "rows": 2},
        ],
        "sections": ["Purpose", "Required Tools", "Safety Precautions",
                     "Detailed Steps", "Verification", "Troubleshooting", "Revision History"],
    },
    "process-doc": {
        "label": "Process Documentation", "category": "ops", "subtitle": "End-to-End Process",
        "accent": "#C5E1A5", "tag": "Process", "icon": "GitBranch",
        "fields": [
            {"name": "Process Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Process Owner", "type": "text"},
            {"name": "Inputs", "type": "textarea", "rows": 2},
            {"name": "Outputs", "type": "textarea", "rows": 2},
            {"name": "Process Steps", "type": "textarea", "rows": 4},
            {"name": "KPIs", "type": "textarea", "rows": 2},
        ],
        "sections": ["Process Purpose", "Scope", "Inputs & Outputs", "Process Map",
                     "Detailed Steps", "Roles", "Controls & Metrics", "Continuous Improvement"],
    },
    "audit-checklist": {
        "label": "Audit Checklist", "category": "ops", "subtitle": "Audit / Compliance Checklist",
        "accent": "#B3E5FC", "tag": "Compliance", "icon": "ShieldCheck",
        "fields": [
            {"name": "Audit Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Standard / Framework", "type": "text", "placeholder": "ISO 9001, SOC 2, GDPR…"},
            {"name": "Areas to Audit", "type": "textarea", "rows": 3},
            {"name": "Evidence Required", "type": "textarea", "rows": 2},
        ],
        "sections": ["Audit Purpose", "Scope", "Reference Standard", "Checklist (Table)",
                     "Sampling Approach", "Findings Template", "Reporting"],
        "guidance": "Checklist (Table) MUST be a Markdown table with columns: # | Area | Control / Question | Evidence Required | Compliant (Y/N/Partial) | Notes. Include 10-15 rows.",
    },

    # ---------------- Manufacturing ----------------
    "quality-procedure": {
        "label": "Quality Procedure", "category": "mfg", "subtitle": "Quality Control Procedure",
        "accent": "#A8E6CF", "tag": "Quality", "icon": "BadgeCheck",
        "fields": [
            {"name": "Procedure Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Applicable Standard", "type": "text"},
            {"name": "Product / Process", "type": "text"},
            {"name": "Quality Requirements", "type": "textarea", "rows": 3},
            {"name": "Inspection Method", "type": "textarea", "rows": 2},
        ],
        "sections": ["Purpose", "Scope", "Reference Documents", "Responsibilities",
                     "Quality Criteria", "Procedure", "Records & Documentation",
                     "Non-Conformance Handling"],
    },
    "inspection-checklist": {
        "label": "Inspection Checklist", "category": "mfg", "subtitle": "Production Inspection",
        "accent": "#FFE45E", "tag": "Inspection", "icon": "Search",
        "fields": [
            {"name": "Product / Line", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Inspection Type", "type": "text", "placeholder": "Incoming / In-Process / Final"},
            {"name": "Key Parameters", "type": "textarea", "rows": 3},
            {"name": "Tolerances", "type": "textarea", "rows": 2},
        ],
        "sections": ["Purpose", "Scope", "Equipment Used", "Inspection Checklist (Table)",
                     "Acceptance Criteria", "Non-Conformance Procedure"],
        "guidance": "Inspection Checklist (Table) must be a Markdown table with columns: # | Parameter | Specification | Method | Acceptance Criteria | Result | Inspector. Include 8-12 rows.",
    },
    "capa-report": {
        "label": "CAPA Report", "category": "mfg", "subtitle": "Corrective & Preventive Action",
        "accent": "#FFB6C1", "tag": "Quality", "icon": "Stethoscope",
        "fields": [
            {"name": "CAPA Title", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Problem Description", "type": "textarea", "rows": 3},
            {"name": "Root Cause (if known)", "type": "textarea", "rows": 2},
            {"name": "Containment Action", "type": "textarea", "rows": 2},
            {"name": "Owner", "type": "text"},
        ],
        "sections": ["Issue Description", "Containment Actions", "Root Cause Analysis",
                     "Corrective Actions", "Preventive Actions", "Verification of Effectiveness",
                     "Closure"],
    },
    "rca": {
        "label": "Root Cause Analysis", "category": "mfg", "subtitle": "5-Why / Fishbone RCA",
        "accent": "#D1C4E9", "tag": "Analysis", "icon": "Microscope",
        "fields": [
            {"name": "Incident / Issue", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Date Occurred", "type": "text"},
            {"name": "Initial Symptoms", "type": "textarea", "rows": 3},
            {"name": "Immediate Impact", "type": "textarea", "rows": 2},
            {"name": "Data Collected", "type": "textarea", "rows": 2},
        ],
        "sections": ["Problem Statement", "Timeline of Events", "Data & Evidence",
                     "5-Why Analysis", "Fishbone Analysis (Ishikawa)",
                     "Identified Root Causes", "Corrective Actions", "Preventive Actions",
                     "Lessons Learned"],
    },
    "maintenance-sop": {
        "label": "Maintenance SOP", "category": "mfg", "subtitle": "Preventive Maintenance SOP",
        "accent": "#C5E1A5", "tag": "Maintenance", "icon": "Cog",
        "fields": [
            {"name": "Equipment / Asset", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Maintenance Type", "type": "text", "placeholder": "Preventive / Predictive / Corrective"},
            {"name": "Frequency", "type": "text"},
            {"name": "Maintenance Steps", "type": "textarea", "rows": 4},
            {"name": "Safety Notes", "type": "textarea", "rows": 2},
        ],
        "sections": ["Purpose", "Scope", "Safety Precautions", "Tools & Materials",
                     "Pre-Maintenance Checks", "Maintenance Steps", "Post-Maintenance Verification",
                     "Records", "Escalation"],
    },
    "safety-procedure": {
        "label": "Safety Procedure", "category": "mfg", "subtitle": "EHS / Safety Procedure",
        "accent": "#FFB6C1", "tag": "Safety", "icon": "HardHat",
        "fields": [
            {"name": "Procedure Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Hazards Addressed", "type": "textarea", "rows": 2},
            {"name": "PPE Required", "type": "textarea", "rows": 2},
            {"name": "Emergency Response", "type": "textarea", "rows": 2},
        ],
        "sections": ["Purpose", "Scope", "Hazard Identification", "Risk Assessment",
                     "Required PPE", "Safe Work Procedure", "Emergency Response",
                     "Training Requirements", "Incident Reporting", "Revision History"],
    },

    # ---------------- HR ----------------
    "hr-policy": {
        "label": "HR Policy", "category": "hr", "subtitle": "Company HR Policy",
        "accent": "#A8C6F7", "tag": "Policy", "icon": "BookOpen",
        "fields": [
            {"name": "Policy Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Applies To", "type": "text"},
            {"name": "Effective Date", "type": "text"},
            {"name": "Policy Intent", "type": "textarea", "rows": 3},
            {"name": "Key Rules", "type": "textarea", "rows": 4},
            {"name": "Consequences of Violation", "type": "textarea", "rows": 2},
        ],
        "sections": ["Purpose", "Scope", "Policy Statement", "Definitions", "Procedure",
                     "Roles & Responsibilities", "Compliance & Enforcement",
                     "Related Documents", "Revision History"],
    },
    "employee-handbook": {
        "label": "Employee Handbook", "category": "hr", "subtitle": "New-hire Handbook",
        "accent": "#FFD3B6", "tag": "Onboarding", "icon": "Book",
        "fields": [
            {"name": "Company Name", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Company Values", "type": "textarea", "rows": 2},
            {"name": "Working Hours / Leave", "type": "textarea", "rows": 2},
            {"name": "Compensation Overview", "type": "textarea", "rows": 2},
            {"name": "Code of Conduct", "type": "textarea", "rows": 2},
        ],
        "sections": ["Welcome Message", "About the Company", "Mission & Values",
                     "Code of Conduct", "Employment Policies", "Compensation & Benefits",
                     "Leave & Time Off", "Workplace Safety", "Performance & Growth",
                     "Grievance Redressal", "Acknowledgement"],
    },
    "onboarding-guide": {
        "label": "Onboarding Guide", "category": "hr", "subtitle": "First 30/60/90 days",
        "accent": "#A8E6CF", "tag": "People", "icon": "UserPlus",
        "fields": [
            {"name": "Role", "type": "text", "required": True},
            {"name": "Department", "type": "text"},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Reporting Manager", "type": "text"},
            {"name": "Key Goals (90 days)", "type": "textarea", "rows": 3},
            {"name": "Tools / Access Required", "type": "textarea", "rows": 2},
        ],
        "sections": ["Welcome & Overview", "Day 1 Checklist", "Week 1 Goals",
                     "First 30 Days", "60-Day Milestones", "90-Day Review",
                     "Key Contacts", "Resources & Tools"],
    },
    "training-doc": {
        "label": "Training Documentation", "category": "hr", "subtitle": "Training Program Doc",
        "accent": "#FFE45E", "tag": "L&D", "icon": "GraduationCap",
        "fields": [
            {"name": "Training Title", "type": "text", "required": True},
            {"name": "Industry", "type": "select", "options": INDUSTRIES},
            {"name": "Target Audience", "type": "text"},
            {"name": "Learning Objectives", "type": "textarea", "rows": 3},
            {"name": "Duration", "type": "text"},
            {"name": "Delivery Method", "type": "text"},
            {"name": "Assessment Approach", "type": "textarea", "rows": 2},
        ],
        "sections": ["Training Overview", "Learning Objectives", "Target Audience",
                     "Curriculum / Modules", "Delivery Plan", "Materials & Resources",
                     "Assessment", "Trainer Notes", "Evaluation & Feedback"],
    },
}


def doc_type_dict():
    """Return frontend-safe dict listing all types grouped by category."""
    grouped = {k: {"label": v, "types": []} for k, v in CATEGORIES.items()}
    for key, cfg in DOC_TYPES.items():
        grouped[cfg["category"]]["types"].append({
            "key": key,
            "category": cfg["category"],
            "label": cfg["label"],
            "subtitle": cfg["subtitle"],
            "accent": cfg["accent"],
            "tag": cfg["tag"],
            "icon": cfg["icon"],
            "fields": cfg["fields"],
            "sections": cfg["sections"],
        })
    return grouped


# ---------------- Document Pipeline ----------------
# Maps a source document type to the list of downstream documents it can feed.
PIPELINE = {
    "brd":         ["frd", "srs", "user-story", "use-case", "project-charter", "scope-document"],
    "frd":         ["srs", "user-story", "use-case", "test-case", "rtm"],
    "srs":         ["user-story", "use-case", "test-case", "test-plan"],
    "user-story":  ["test-case", "rtm"],
    "use-case":    ["test-case", "test-plan", "rtm"],
    "test-case":   ["test-plan", "rtm", "defect-report"],
    "test-plan":   ["test-case", "rtm"],
    "project-charter": ["scope-document", "stakeholder-matrix", "risk-register", "raid-log"],
    "rca":         ["capa-report"],
    "capa-report": ["quality-procedure"],
    "sop":         ["work-instruction", "audit-checklist"],
}
